# Generated by Django 5.1.4 on 2025-02-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_id", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=512)),
                ("markdown", models.CharField(max_length=255)),
                ("html", models.CharField(max_length=512)),
                ("published", models.DateTimeField(verbose_name="date published")),
                ("updated", models.DateTimeField(verbose_name="date published")),
                ("img", models.CharField(max_length=100)),
                ("dir", models.CharField(max_length=100)),
                ("html2", models.CharField(max_length=255)),
                ("html3", models.CharField(max_length=255)),
                ("img2", models.CharField(max_length=100)),
                ("img3", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Entries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_id", models.IntegerField(default=0)),
                ("slug", models.CharField(default=" ", max_length=100)),
                ("title", models.CharField(max_length=512)),
                ("markdown", models.CharField(max_length=255)),
                ("html", models.CharField(max_length=512)),
                ("published", models.DateTimeField(verbose_name="date published")),
                ("updated", models.DateTimeField(verbose_name="date published")),
                ("img", models.CharField(max_length=100)),
                ("dir", models.CharField(max_length=100)),
                ("html2", models.CharField(max_length=255)),
                ("html3", models.CharField(max_length=255)),
                ("img2", models.CharField(max_length=100)),
                ("img3", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="EntriesHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_id", models.IntegerField(default=0)),
                ("slug", models.CharField(default=" ", max_length=100)),
                ("title", models.CharField(max_length=512)),
                ("markdown", models.CharField(max_length=255)),
                ("html", models.CharField(max_length=512)),
                ("published", models.DateTimeField(verbose_name="date published")),
                ("updated", models.DateTimeField(verbose_name="date published")),
                ("img", models.CharField(max_length=100)),
                ("dir", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=24)),
                ("img", models.CharField(max_length=100)),
                ("titolo", models.CharField(max_length=64)),
                ("descrizione", models.CharField(default=" ", max_length=512)),
                ("link", models.CharField(max_length=512)),
                ("attivo", models.IntegerField(default=0)),
                ("width", models.CharField(default=" ", max_length=6)),
                ("height", models.CharField(default=" ", max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="Menuweb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=20)),
                ("radice", models.CharField(max_length=20)),
                ("livello", models.IntegerField(default=0)),
                ("titolo", models.CharField(max_length=64)),
                ("descrizione", models.CharField(max_length=256)),
                ("link", models.CharField(max_length=512)),
                ("attivo", models.IntegerField(default=0)),
                ("icon", models.CharField(max_length=255)),
                ("workplace", models.IntegerField(default=0)),
                ("param1", models.CharField(max_length=255)),
                ("ordine", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=24)),
                ("img", models.CharField(max_length=100)),
                ("titolo", models.CharField(max_length=64)),
                ("caption", models.CharField(max_length=512)),
                ("link", models.CharField(max_length=512)),
            ],
        ),
    ]
