# Generated by Django 5.1.4 on 2025-02-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0002_alter_links_height_alter_links_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="links",
            name="height",
            field=models.CharField(default="5%", max_length=6),
        ),
        migrations.AlterField(
            model_name="links",
            name="width",
            field=models.CharField(default="5%", max_length=6),
        ),
    ]
