# Generated by Django 5.1.4 on 2025-01-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0008_remove_slider_id_slider_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=24)),
                ("img", models.CharField(max_length=100)),
                ("titolo", models.CharField(max_length=64)),
                ("descrisione", models.CharField(max_length=512)),
                ("link", models.CharField(max_length=512)),
                ("attivo", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="slider",
            name="ID",
        ),
        migrations.AddField(
            model_name="slider",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
