# Generated by Django 5.1.4 on 2025-01-31 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0009_links_remove_slider_id_slider_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="links",
            old_name="descrisione",
            new_name="descrizione",
        ),
    ]
