# Generated by Django 5.2 on 2025-05-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0004_slider_testo"),
        ("beb", "0011_links_descrisione"),
    ]

    operations = []
