# Generated by Django 5.2 on 2025-05-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0012_merge_0004_slider_testo_0011_links_descrisione"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="links",
            name="descrisione",
        ),
        migrations.AlterField(
            model_name="links",
            name="descrizione",
            field=models.CharField(default=" ", max_length=512),
        ),
    ]
