# Generated by Django 5.2.1 on 2025-06-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0015_food"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="indirizzo",
            field=models.CharField(default=" ", max_length=64),
        ),
        migrations.AddField(
            model_name="food",
            name="telefono",
            field=models.CharField(default=" ", max_length=64),
        ),
    ]
