# Generated by Django 5.2.4 on 2025-10-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0017_food_apiedi"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="codice2",
            field=models.CharField(default=" ", max_length=24),
            preserve_default=False,
        ),
    ]
