# Generated by Django 6.0.7 on 2026-07-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0019_menuweb"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="tipopage",
            field=models.CharField(default=" ", max_length=50),
        ),
    ]
