# Generated by Django 6.0.7 on 2026-08-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0020_menu_tipopage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=20)),
                ("radice", models.CharField(max_length=20)),
                ("livello", models.IntegerField(default=0)),
                ("titolo", models.CharField(max_length=64)),
                ("descrizione", models.CharField(max_length=256)),
                ("link", models.CharField(max_length=512)),
                ("attivo", models.IntegerField(default=0)),
                ("icon", models.CharField(max_length=255)),
                ("workplace", models.IntegerField(default=0)),
                ("param1", models.CharField(max_length=255)),
                ("ordine", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="Menuweb",
        ),
    ]
