# Generated by Django 5.1.4 on 2025-01-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0004_entries_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntriesHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_id", models.IntegerField(default=0)),
                ("slug", models.CharField(default=" ", max_length=100)),
                ("title", models.CharField(max_length=512)),
                ("markdown", models.CharField(max_length=255)),
                ("html", models.CharField(max_length=512)),
                ("published", models.DateTimeField(verbose_name="date published")),
                ("updated", models.DateTimeField(verbose_name="date published")),
                ("img", models.CharField(max_length=100)),
                ("dir", models.CharField(max_length=100)),
                ("html2", models.CharField(max_length=255)),
                ("html3", models.CharField(max_length=255)),
                ("img2", models.CharField(max_length=100)),
                ("img3", models.CharField(max_length=100)),
            ],
        ),
    ]
