# Generated by Django 5.1.4 on 2025-01-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0007_slider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slider",
            name="id",
        ),
        migrations.AddField(
            model_name="slider",
            name="ID",
            field=models.AutoField(default=16, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
