# Generated by Django 5.1.4 on 2025-02-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0003_alter_links_height_alter_links_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="testo",
            field=models.CharField(default="", max_length=2048),
            preserve_default=False,
        ),
    ]
