# Generated by Django 5.1.4 on 2025-01-05 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0005_entrieshome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrieshome",
            name="html2",
        ),
        migrations.RemoveField(
            model_name="entrieshome",
            name="html3",
        ),
        migrations.RemoveField(
            model_name="entrieshome",
            name="img2",
        ),
        migrations.RemoveField(
            model_name="entrieshome",
            name="img3",
        ),
    ]
