# Generated by Django 5.1.4 on 2025-03-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0004_slider_testo"),
        ("beb", "0011_links_descrisione"),
    ]

    operations = []
