# Generated by Django 6.1 on 2026-08-26 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created"],
                "verbose_name": "Ordine",
                "verbose_name_plural": "Ordini",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Articolo ordine",
                "verbose_name_plural": "Articoli ordine",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(
                default="Italia", max_length=100, verbose_name="Paese"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data consegna"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data pagamento"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                default="paypal", max_length=20, verbose_name="Metodo di pagamento"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                default="pending", max_length=20, verbose_name="Stato pagamento"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefono"),
        ),
        migrations.AddField(
            model_name="order",
            name="province",
            field=models.CharField(blank=True, max_length=2, verbose_name="Provincia"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data spedizione"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Costo spedizione",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_notes",
            field=models.TextField(blank=True, verbose_name="Note di spedizione"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("bank_transfer", "Bonifico bancario"),
                    ("cash_on_delivery", "Contrassegno"),
                ],
                default="paypal",
                max_length=20,
                verbose_name="Metodo di pagamento",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=250, verbose_name="Indirizzo"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Città"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data creazione"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Cognome"),
        ),
        migrations.AlterField(
            model_name="order",
            name="paypal_transaction_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ID transazione PayPal"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(max_length=20, verbose_name="CAP"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "In Attesa"),
                    ("processing", "In Lavorazione"),
                    ("paid", "Pagato"),
                    ("shipped", "Spedito"),
                    ("delivered", "Consegnato"),
                    ("cancelled", "Cancellato"),
                    ("refunded", "Rimborsato"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Stato",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Totale"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data aggiornamento"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
