# Generated by Django 6.1 on 2026-09-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paypal_order_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID ordine PayPal"
                    ),
                ),
                (
                    "paypal_transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID transazione PayPal"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Creata"),
                            ("approved", "Approvata"),
                            ("completed", "Completata"),
                            ("failed", "Fallita"),
                            ("refunded", "Rimborsata"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Importo"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Valuta"
                    ),
                ),
                (
                    "payer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email pagatore"
                    ),
                ),
                (
                    "payer_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome pagatore"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transazione PayPal",
                "verbose_name_plural": "Transazioni PayPal",
            },
        ),
    ]
