# Generated by Django 6.1 on 2026-08-26 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefono"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Indirizzo"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="CAP"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Città"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Provincia"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Italia", max_length=100, verbose_name="Paese"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data di nascita"
                    ),
                ),
                (
                    "newsletter",
                    models.BooleanField(
                        default=False, verbose_name="Iscritto alla newsletter"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profilo utente",
                "verbose_name_plural": "Profili utente",
            },
        ),
    ]
