# Generated by Django 5.1.4 on 2025-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="links",
            name="height",
            field=models.CharField(default="20%", max_length=6),
        ),
        migrations.AlterField(
            model_name="links",
            name="width",
            field=models.CharField(default="20%", max_length=6),
        ),
    ]
