# Generated by Django 5.2.1 on 2025-06-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0014_delete_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=24)),
                ("img", models.CharField(max_length=100)),
                ("titolo", models.CharField(max_length=64)),
                ("descrizione", models.CharField(default=" ", max_length=512)),
                ("link", models.CharField(max_length=512)),
                ("attivo", models.IntegerField(default=0)),
                ("width", models.CharField(default="5%", max_length=6)),
                ("height", models.CharField(default="5%", max_length=6)),
            ],
        ),
    ]
