# Generated by Django 5.2.1 on 2025-06-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0016_food_indirizzo_food_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="apiedi",
            field=models.CharField(default=" ", max_length=4),
        ),
    ]
