# Generated by Django 6.1 on 2026-08-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_category_slug_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorie",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created"],
                "verbose_name": "Pipe",
                "verbose_name_plural": "Pipe",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="bowl_diameter_mm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="finish",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="is_unique",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="length_cm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(default="Radica", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_grams",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="year_made",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=1),
        ),
    ]
