# Generated by Django 6.1 on 2026-08-25 20:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="length_cm",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrizione"),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/%Y/%m/%d",
                verbose_name="Immagine",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="bowl_depth_mm",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Profondità fornello (mm)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="filter",
            field=models.BooleanField(default=False, verbose_name="Filtro"),
        ),
        migrations.AddField(
            model_name="product",
            name="filter_size",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Misura filtro (mm)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="height_mm",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Altezza (mm)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/%Y/%m/%d",
                verbose_name="Immagine 2",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/%Y/%m/%d",
                verbose_name="Immagine 3",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_4",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/%Y/%m/%d",
                verbose_name="Immagine 4",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="length_mm",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Lunghezza (mm)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numero di serie"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shape",
            field=models.CharField(
                choices=[
                    ("dritta", "Dritta"),
                    ("curva", "Curva"),
                    ("mezza_curva", "Mezza Curva"),
                    ("churchwarden", "Churchwarden"),
                    ("poker", "Poker"),
                    ("billiard", "Billiard"),
                    ("dublin", "Dublin"),
                    ("bulldog", "Bulldog"),
                    ("prince", "Prince"),
                    ("apple", "Apple"),
                    ("pot", "Pot"),
                    ("canadian", "Canadian"),
                    ("lumberman", "Lumberman"),
                    ("freehand", "Freehand"),
                    ("custom", "Custom"),
                ],
                default="dritta",
                max_length=20,
                verbose_name="Forma",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Disponibile"),
        ),
        migrations.AlterField(
            model_name="product",
            name="bowl_diameter_mm",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Diametro fornello (mm)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.category",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data creazione"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Descrizione"),
        ),
        migrations.AlterField(
            model_name="product",
            name="finish",
            field=models.CharField(
                choices=[
                    ("liscia", "Liscia"),
                    ("sabbiata", "Sabbiata"),
                    ("rustica", "Rustica"),
                    ("liscia_sabbiata", "Liscia/Sabbiata"),
                    ("levigata", "Levigata"),
                    ("naturale", "Naturale"),
                ],
                default="liscia",
                max_length=20,
                verbose_name="Finitura",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/%Y/%m/%d",
                verbose_name="Immagine principale",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_unique",
            field=models.BooleanField(default=True, verbose_name="Pezzo unico"),
        ),
        migrations.AlterField(
            model_name="product",
            name="material",
            field=models.CharField(
                choices=[
                    ("radica", "Radica"),
                    ("morta", "Radica Morta"),
                    ("oliva", "Oliva"),
                    ("ciliegio", "Ciliegio"),
                    ("noce", "Noce"),
                    ("quercia", "Quercia"),
                    ("acero", "Acero"),
                    ("ebano", "Ebano"),
                ],
                default="radica",
                max_length=20,
                verbose_name="Materiale",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Prezzo"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Disponibilità",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data aggiornamento"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight_grams",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Peso (grammi)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="year_made",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Anno realizzazione"
            ),
        ),
    ]
