INSERT INTO blog (id,author_id,title,markdown,html,published,updated,img,dir,html2,html3,img2,img3) VALUES
	 (1,1,'Prestige 1','Un ricco programma che accompagnerà sanpierini e visitatori da giugno a settembre, nel segno dell’arte, come occasione di ripartenza. E’ davvero ricco il programma di “Venerdì a Villa Adami”, l’iniziativa proposta dalla locale Pro Loco e dal “CCN de’ Medici”, che valorizzerà una delle aree più belle di San Piero a Sieve. Il tutto per dimostrare la propria voglia di non fermarsi, di andare avanti, ma tutto nel rispetto delle norme e senza prendere rischi per spettatori e partecipanti. Una manifestazione che ha avuto il patrocinio del Comune di Scarperia e San Piero ','Un ricco programma che accompagnerà sanpierini e visitatori da giugno a settembre, nel segno dell’arte, come occasione di ripartenza. E’ davvero ricco il programma di “Venerdì a Villa Adami”, l’iniziativa proposta dalla locale Pro Loco e dal “CCN de’ Medici”, che valorizzerà una delle aree più belle di San Piero a Sieve. Il tutto per dimostrare la propria voglia di non fermarsi, di andare avanti, ma tutto nel rispetto delle norme e senza prendere rischi per spettatori e partecipanti. Una manifestazione che ha avuto il patrocinio del Comune di Scarperia e San Piero

Il primo appuntamento previsto è per venerdì 18 Giugno, con “Francesco Nuti. Andata, caduta e ritorno”, scritto e diretto da Valerio Groppa, con Nicola Pecci, le musiche di Giovanni e Francesco Nuti, tratto dall''autobiografia di Francesco Nuti "Sono un bravo ragazzo". Sabato 19 Giugno (alle 17) sarà la volta di “Dante e il Mugello”: Carlo Forasassi conversa con il Dott. Fabrizio Boni, a 700 anni dalla morte di Dante, ad ingresso gratuito. Venerdì 25 Giugno musica protagonista con “Jazz standard band”, con un trio di eccezione composto da Franco Baggiani alla tromba, Alessandro Bruno alla chitarra e Alessandro Geri al contrabbasso. Il giorno seguente sarà la volta del concerto dei “Polimeri Variabili”, con musica prevalentemente funky. Luglio si aprirà il 2 con “I Geneticamente mortificati” in “Restauration. Siamo tornati di moda” monologo imperfetto sull''attualità, scritto da Marco Giavatto e diretto da Fulvio Ferrati. Si proseguirà venerdì 9 Luglio

con “Piccoli crimini coniugali” di Eric Emmanuel Schmitt con Fabrizio Pinzauti e Rosanna Reccia ed il 16 con “La Divina Commedia in 100 luoghi - Inferno Canto XV” performance di Matteo Fratarcangeli. Venerdì 23 Luglio “Musica 60-70-80-90 con Altri Tempi” ad ingresso gratuito ed a chiuder e il mese, il 30, “Dante. Viaggio dentro e intorno alla Divina Commedia” con Gianluigi Tosto. Due gli appuntamenti in agosto: il 6 con “Itaglia” con Matteo Procuranti e Silvia Cuncu per la regia di Virginia Martini ed il 27 “Alla radio con Čechov si può anche ridere” da un''idea di Pietro Venè, con I Pinguini e la regia di Pietro Venè e Cristina Bacci. Venerdì 3 Settembre “New Orleans history” quintetto di fiati e percussioni ed a chiudere, ad ingresso gratuito, venerdì 10 Settembre “Musica dal vivo” con Ivo e Sofia.

“Si tratta di un programma che spazia tra arti e generi molto diversi, spiega soddisfatto il presidente della Pro Loco di San Piero, Sauro Bani, che abbiamo cercato di mettere insieme per accontentare gusti e persone differenti. C’era bisogno di qualcosa che, in sicurezza, ridesse vita alle arti e possibilità di aggregarsi. L’esperienza molto positiva in Villa Adami dello scorso anno ci ha spinto a far crescere questa idea ed a riproporla, diversificando le possibilità di quello che è uno dei luoghi di ritrovo più belli e caratteristici del nostro paese.”

L’accesso, regolamentato, agli spettacoli, avrà un costo di 8 euro a serata (4 euro il ridotto) tranne alcuni appuntamenti ove sia indicato specificatamente l’ingresso gratuito. Le serate, che saranno singolarmente annullate in caso di maltempo, hanno inizio alle 21, prevedono una prenotazione obbligatoria per mail a   prolocosanpieroasieve@gmail.com o attraverso whatsapp al 3382562225 o al 3311090673.','2022-05-09 17:53:34','2022-05-09 17:53:34','prestige1.jpg','/blogs/img','Un ricco programma che accompagnerà sanpierini e visitatori da giugno a settembre, nel segno dell’arte, come occasione di ripartenza...
','Un ricco programma che accompagnerà sanpierini e visitatori da giugno a settembre, nel segno dell’arte, come occasione di ripartenza. E’ davvero ricco il programma di “Venerdì a Villa Adami”, l’iniziativa proposta dalla locale Pro Loco e dal “CCN de’ Medici”, che valorizzerà una delle aree più belle di San Piero a Sieve. Il tutto per dimostrare la propria voglia di non fermarsi, di andare avanti, ma tutto nel rispetto delle norme e senza prendere rischi per spettatori e partecipanti. Una manifestazione che ha avuto il patrocinio del Comune di Scarperia e San Piero ','Villa Adami Venerdi 2021.jpg','Villa Adami Venerdi 2021.jpg'),
	 (2,1,'Prestige 2','Si è aperto il bando per il 17° Simposio dedicato allo scultore Antonio Berti','Dal 14 al 25 settembre San Piero a Sieve ospiterà la diciassettesima edizione del Simposio di Scultura "Premio Antonio Berti", evento biennale dedicato all''arte che vede coinvolti gli studenti delle più importanti Accademie di Belle Arti italiane ed europee che si sfideranno a “colpi di scalpello” nel parco dedicato proprio all’artista sanpierino (nell’anno in cui la cittadina sarà ufficialmente “intitolata” con la posa di cartelli all’ingresso del centro abitato con su scritto “paese natale di Antonio Berti”).

La manifestazione, promossa dalla Proloco di San Piero a Sieve, con il Patrocinio del Comune di Scarperia e San Piero e della Regione Toscana e con la collaborazione dell''Accademia di Belle Arti di Firenze e di quella di Carrara, il Comune di Firenzuola, l''Unione Montana dei Comuni del Mugello e la Fondazione per la Scultura Antonio Berti, vede il coinvolgimento anche dell’Ente Cassa di Risparmio di Firenze che ha finanziato il progetto di simposio e del percorso ad esso correlato. Il Simposio di Scultura nasce dalla volontà di rendere omaggio alla figura del grande scultore e conterraneo Antonio Berti, profondamente legato alla sua terra. ','2022-05-09 21:29:38','2022-05-09 21:29:38','prestige2.jpg','/blogs/img','Per dieci giorni i sei studenti realizzano opere scultoree contemporanee, a tema libero, utilizzando blocchi di pietra serena, grazie al Copser, provenienti dalle cave di Firenzuola (che ospiteranno, in uno dei giorni del Simposio, ','La novità di quest’anno sarà la creazione di una categoria speciale, che quest’anno sarà dedicata ai 700 anni dalla morte di Dante, a cui un artista, invitato fra chi ha partecipato in questi anni (e sono oltre 100), dovrà ispirarsi per scolpire un’opera più grande delle altre, fuori concorso, con 15 giorni a disposizione.

Molte delle sculture realizzate nelle precedenti edizioni hanno trovato collocazione nel tessuto urbano di San Piero a Sieve, valorizzandone parchi, piazze e giardini. E questo ha dato vita all’idea del percorso che finalmente dovrebbe trovare un compimento. La Pro Loco, insieme con il Centro Commerciale de'' Medici, ha creato un progetto che intende valorizzare l''abitato di San Piero a Sieve, già ricco di beni architettonici e storici di rilievo, attraverso la collocazione delle opere realizzate in questi anni. Lo sviluppo di tale percorso, che unirà in particolare la Stazione di San Piero con lo stesso Parco Berti, prevede la riqualificazione delle aree interessate e la collocazione di cartellonistica che, oltre ad indicare il percorso, guidi il visitatore alla scoperta degli angoli più suggestivi del paese: la Pieve millenaria dedicata a San Pietro, la Fortezza di San Martino, Villa Adami, Villa Schifanoia, la Torre medicea di Scoronconcolo, guidati in un percorso ideale che ha le sculture di pietra come filo conduttore. Un progetto ambizioso, ma già ben avviato, nel quale la Pro Loco crede molto.

“Quest’anno, spiega il presidente della Pro Loco sanpierina, Sauro Bani, si fa un ulteriore salto di qualità dando impulso al Simposio, e partendo con il percorso, attraverso il tessuto urbano sanpierino, e con questa nuova sezione, con un artista affermato e che già a San Piero ha dimostrato il suo valore, volgiamo rafforzare il legame di San Piero con la scultura e l’arte, cosa che cerchiamo di far emergere da tutte le nostre iniziative.”','simposio5.jpg','simposio 4.jpg'),
	 (3,2,'Prestige 3','a','2	1	Si è aperto il bando per il 17° Simposio dedicato allo scultore Antonio Berti	Si è aperto il bando per il 17° Simposio dedicato allo scultore Antonio Berti	Si è aperto il bando per il 17° Simposio dedicato allo scultore Antonio Berti	"Dal 14 al 25 settembre San Piero a Sieve ospiterà la diciassettesima edizione del Simposio di Scultura "Premio Antonio Berti", evento biennale dedicato all''arte che vede coinvolti gli studenti delle più importanti Accademie di Belle Arti italiane ed europee che si sfideranno a “colpi di scalpello” nel parco dedicato proprio all’artista sanpierino (nell’anno in cui la cittadina sarà ufficialmente “intitolata” con la posa di cartelli all’ingresso del centro abitato con su scritto “paese natale di Antonio Berti”).

La manifestazione, promossa dalla Proloco di San Piero a Sieve, con il Patrocinio del Comune di Scarperia e San Piero e della Regione Toscana e con la collaborazione dell''Accademia di Belle Arti di Firenze e di quella di Carrara, il Comune di Firenzuola, l''Unione Montana dei Comuni del Mugello e la Fondazione per la Scultura Antonio Berti, vede il coinvolgimento anche dell’Ente Cassa di Risparmio di Firenze che ha finanziato il progetto di simposio e del percorso ad esso correlato. Il Simposio di Scultura nasce dalla volontà di rendere omaggio alla figura del grande scultore e conterraneo Antonio Berti, profondamente legato alla sua terra. "	2021-06-08 00:00:00	2021-06-10 22:25:38	simposio 4.jpg	/news/img	"Per dieci giorni i sei studenti realizzano opere scultoree contemporanee, a tema libero, utilizzando blocchi di pietra serena, grazie al Copser, provenienti dalle cave di Firenzuola (che ospiteranno, in uno dei giorni del Simposio, una visita guidata degli artisti, alcuni scatti dei quali saranno poi presentati in occasione della premiazione), lavorando presso il laboratorio all''aperto allestito presso il Parco Antonio Berti, dove sarà possibile vederli all''opera per tutta la durata della manifestazione. Per partecipare è appena aperto il bando, con scadenza sabato 26 giugno. Gli artisti ammessi, dopo una valutazione di una apposita commissione artistica che vede anche professori delle Accademie, guidati in particolare dal professor Di Tommaso dell''Accademia delle Belle Arti di Firenze, saranno ospitati per l’intera durata della manifestazione dal Camping Village Mugello Verde. L''atmosfera è unica: una nube di polvere bianca, dovuta alla lavorazione della pietra con mola e scalpelli, avvolge gli scultori concentrati nel tirar fuori in poco tempo un''opera di grande impatto visivo ed emotivo. Anche molto spettacolare, tanto è vero che, insieme ad Unione dei Comuni, è stato intrapreso un percorso di coinvolgimento dei plessi scolastici delle scuole medie inferiori e superiori del territorio, con apposite visite guidate. L’accesso per il pubblico è ovviamente libero.

simposio5"	"La novità di quest’anno sarà la creazione di una categoria speciale, che quest’anno sarà dedicata ai 700 anni dalla morte di Dante, a cui un artista, invitato fra chi ha partecipato in questi anni (e sono oltre 100), dovrà ispirarsi per scolpire un’opera più grande delle altre, fuori concorso, con 15 giorni a disposizione.

Molte delle sculture realizzate nelle precedenti edizioni hanno trovato collocazione nel tessuto urbano di San Piero a Sieve, valorizzandone parchi, piazze e giardini. E questo ha dato vita all’idea del percorso che finalmente dovrebbe trovare un compimento. La Pro Loco, insieme con il Centro Commerciale de'' Medici, ha creato un progetto che intende valorizzare l''abitato di San Piero a Sieve, già ricco di beni architettonici e storici di rilievo, attraverso la collocazione delle opere realizzate in questi anni. Lo sviluppo di tale percorso, che unirà in particolare la Stazione di San Piero con lo stesso Parco Berti, prevede la riqualificazione delle aree interessate e la collocazione di cartellonistica che, oltre ad indicare il percorso, guidi il visitatore alla scoperta degli angoli più suggestivi del paese: la Pieve millenaria dedicata a San Pietro, la Fortezza di San Martino, Villa Adami, Villa Schifanoia, la Torre medicea di Scoronconcolo, guidati in un percorso ideale che ha le sculture di pietra come filo conduttore. Un progetto ambizioso, ma già ben avviato, nel quale la Pro Loco crede molto.

“Quest’anno, spiega il presidente della Pro Loco sanpierina, Sauro Bani, si fa un ulteriore salto di qualità dando impulso al Simposio, e partendo con il percorso, attraverso il tessuto urbano sanpierino, e con questa nuova sezione, con un artista affermato e che già a San Piero ha dimostrato il suo valore, volgiamo rafforzare il legame di San Piero con la scultura e l’arte, cosa che cerchiamo di far emergere da tutte le nostre iniziative.”"	simposio5.jpg	simposio 4.jpg','2022-05-09 21:31:13','2022-05-09 21:31:13','prestige3.jpg','/blogs/img','Si è aperto il bando per il 17° Simposio dedicato allo scultore Antonio Berti	Si è aperto il bando per il 17° Simposio dedicato allo scultore Antonio Berti	"Dal 14 al 25 settembre San Piero a Sieve ospiterà la diciassettesima edizione del Simposio di Scultura "Premio Antonio Berti",','2	1	Si è aperto il bando per il 17° Simposio dedicato allo scultore Antonio Berti	Si è aperto il bando per il 17° Simposio dedicato allo scultore Antonio Berti	Si è aperto il bando per il 17° Simposio dedicato allo scultore Antonio Berti	"Dal 14 al 25 settembre San Piero a Sieve ospiterà la diciassettesima edizione del Simposio di Scultura "Premio Antonio Berti", evento biennale dedicato all''arte che vede coinvolti gli studenti delle più importanti Accademie di Belle Arti italiane ed europee che si sfideranno a “colpi di scalpello” nel parco dedicato proprio all’artista sanpierino (nell’anno in cui la cittadina sarà ufficialmente “intitolata” con la posa di cartelli all’ingresso del centro abitato con su scritto “paese natale di Antonio Berti”).

La manifestazione, promossa dalla Proloco di San Piero a Sieve, con il Patrocinio del Comune di Scarperia e San Piero e della Regione Toscana e con la collaborazione dell''Accademia di Belle Arti di Firenze e di quella di Carrara, il Comune di Firenzuola, l''Unione Montana dei Comuni del Mugello e la Fondazione per la Scultura Antonio Berti, vede il coinvolgimento anche dell’Ente Cassa di Risparmio di Firenze che ha finanziato il progetto di simposio e del percorso ad esso correlato. Il Simposio di Scultura nasce dalla volontà di rendere omaggio alla figura del grande scultore e conterraneo Antonio Berti, profondamente legato alla sua terra. "	2021-06-08 00:00:00	2021-06-10 22:25:38	simposio 4.jpg	/news/img	"Per dieci giorni i sei studenti realizzano opere scultoree contemporanee, a tema libero, utilizzando blocchi di pietra serena, grazie al Copser, provenienti dalle cave di Firenzuola (che ospiteranno, in uno dei giorni del Simposio, una visita guidata degli artisti, alcuni scatti dei quali saranno poi presentati in occasione della premiazione), lavorando presso il laboratorio all''aperto allestito presso il Parco Antonio Berti, dove sarà possibile vederli all''opera per tutta la durata della manifestazione. Per partecipare è appena aperto il bando, con scadenza sabato 26 giugno. Gli artisti ammessi, dopo una valutazione di una apposita commissione artistica che vede anche professori delle Accademie, guidati in particolare dal professor Di Tommaso dell''Accademia delle Belle Arti di Firenze, saranno ospitati per l’intera durata della manifestazione dal Camping Village Mugello Verde. L''atmosfera è unica: una nube di polvere bianca, dovuta alla lavorazione della pietra con mola e scalpelli, avvolge gli scultori concentrati nel tirar fuori in poco tempo un''opera di grande impatto visivo ed emotivo. Anche molto spettacolare, tanto è vero che, insieme ad Unione dei Comuni, è stato intrapreso un percorso di coinvolgimento dei plessi scolastici delle scuole medie inferiori e superiori del territorio, con apposite visite guidate. L’accesso per il pubblico è ovviamente libero.

simposio5"	"La novità di quest’anno sarà la creazione di una categoria speciale, che quest’anno sarà dedicata ai 700 anni dalla morte di Dante, a cui un artista, invitato fra chi ha partecipato in questi anni (e sono oltre 100), dovrà ispirarsi per scolpire un’opera più grande delle altre, fuori concorso, con 15 giorni a disposizione.

Molte delle sculture realizzate nelle precedenti edizioni hanno trovato collocazione nel tessuto urbano di San Piero a Sieve, valorizzandone parchi, piazze e giardini. E questo ha dato vita all’idea del percorso che finalmente dovrebbe trovare un compimento. La Pro Loco, insieme con il Centro Commerciale de'' Medici, ha creato un progetto che intende valorizzare l''abitato di San Piero a Sieve, già ricco di beni architettonici e storici di rilievo, attraverso la collocazione delle opere realizzate in questi anni. Lo sviluppo di tale percorso, che unirà in particolare la Stazione di San Piero con lo stesso Parco Berti, prevede la riqualificazione delle aree interessate e la collocazione di cartellonistica che, oltre ad indicare il percorso, guidi il visitatore alla scoperta degli angoli più suggestivi del paese: la Pieve millenaria dedicata a San Pietro, la Fortezza di San Martino, Villa Adami, Villa Schifanoia, la Torre medicea di Scoronconcolo, guidati in un percorso ideale che ha le sculture di pietra come filo conduttore. Un progetto ambizioso, ma già ben avviato, nel quale la Pro Loco crede molto.

“Quest’anno, spiega il presidente della Pro Loco sanpierina, Sauro Bani, si fa un ulteriore salto di qualità dando impulso al Simposio, e partendo con il percorso, attraverso il tessuto urbano sanpierino, e con questa nuova sezione, con un artista affermato e che già a San Piero ha dimostrato il suo valore, volgiamo rafforzare il legame di San Piero con la scultura e l’arte, cosa che cerchiamo di far emergere da tutte le nostre iniziative.”"	simposio5.jpg	simposio 4.jpg','simposio5.jpg','simposio5.jpg'),
	 (4,1,'Prestige 4','b','In un momento di grande difficoltà per il mondo del volontariato e dell’associazionismo, la Pro Loco di San Piero non si è mai fermata. Aiutando istituzioni e singoli cittadini anche nel momento della pandemia, con consegna delle spese e iniziative mirate, e programmando quelle che saranno le iniziative alla ripresa. Uno sforzo notevole, che ha partorito un calendario ricco di appuntamenti quando tali eventi saranno nuovamente realizzabili. Un impegno che richiede un numero importante di volontari, per i quali le porte sono sempre aperte. Ed anche di risorse, che sono necessarie per “mettere a terra” le tante idee che emergono. ','2022-05-09 21:13:54','2022-05-09 21:13:54','prestige4.jpg','/blogs/img','In un momento di grande difficoltà per il mondo del volontariato e dell’associazionismo, la Pro Loco di San Piero non si è mai fermata.','Per questo la Pro Loco di San Piero ha bisogno dell’aiuto di tutti, attraverso il tesseramento annuale, ancora aperto, e magari anche con la donazione del 5 per mille.

Il tesseramento si potrà effettuare in sede, in via Cipriani 8, tutte le mattine, dalle 10 alle 12, martedì escluso, o, nello stesso orario, sabato e domenica prossimi, in un banchetto appositamente realizzato nei pressi dell’edicola di Via Provinciale.

Ricordiamo che la tessera UNPLI garantisce numerosi vantaggi.

Per quanto riguarda il 5 per mille sarà sufficiente indicare nell’apposita casella della dichiarazione dei redditi, il codice fiscale 05235460481.','ProlocoSPS_tesseramento_2021.jpg','ProlocoSPS_tesseramento_2021.jpg'),
	 (5,2,'Prestige 5','markdown','Descrizione Prima News','2022-05-09 17:53:34','2022-05-09 17:53:34','prestige5.jpg','/blogs/img','html2','html3','img2','img3'),
	 (6,2,'Prestige 6','markdown','descrizione news  img','2022-05-09 17:53:34','2022-05-09 17:53:34','prestige6.jpg','/blogs/img/','html2','html3','img2','img3'),
	 (7,2,'Prestige 7','markdown','Adesso Funziona tutto abbastanza bene11','2022-05-09 17:53:34','2022-05-09 17:53:34','prestige7.jpg','/blogs/img/','html2','html3','img2','img3'),
	 (8,2,'Prestige 8','Si, adesso funziona decisamente neglio.','Si, adesso funziona decisamente neglio.','2022-05-09 17:53:35','2022-05-09 17:53:35','prestige8.jpg','/blogs/img/','html2','html3','img2','img3'),
	 (9,2,'Prestige 16','Descrizione Inserimento NEWS da carlozanieri.it','Descrizione Inserimento NEWS da carlozanieri.it','2022-05-09 17:53:35','2022-05-09 17:53:35','prestige16.jpg','/blogs/img/','html2','html3','img2','img3'),
	 (10,2,'Prestige 10','descrizione uova news da carlozanieri.it','descrizione uova news da carlozanieri.it','2022-05-09 17:53:35','2022-05-09 17:53:35','prestige10.jpg','/blogs/img/','html2','html3','img2','img3');
INSERT INTO blog (id,author_id,title,markdown,html,published,updated,img,dir,html2,html3,img2,img3) VALUES
	 (11,1,'Prestige 1','Un ricco programma che accompagnerà sanpierini e visitatori da giugno a settembre, nel segno dell’arte, come occasione di ripartenza. E’ davvero ricco il programma di “Venerdì a Villa Adami”, l’iniziativa proposta dalla locale Pro Loco e dal “CCN de’ Medici”, che valorizzerà una delle aree più belle di San Piero a Sieve. Il tutto per dimostrare la propria voglia di non fermarsi, di andare avanti, ma tutto nel rispetto delle norme e senza prendere rischi per spettatori e partecipanti. Una manifestazione che ha avuto il patrocinio del Comune di Scarperia e San Piero ','Un ricco programma che accompagnerà sanpierini e visitatori da giugno a settembre, nel segno dell’arte, come occasione di ripartenza. E’ davvero ricco il programma di “Venerdì a Villa Adami”, l’iniziativa proposta dalla locale Pro Loco e dal “CCN de’ Medici”, che valorizzerà una delle aree più belle di San Piero a Sieve. Il tutto per dimostrare la propria voglia di non fermarsi, di andare avanti, ma tutto nel rispetto delle norme e senza prendere rischi per spettatori e partecipanti. Una manifestazione che ha avuto il patrocinio del Comune di Scarperia e San Piero

Il primo appuntamento previsto è per venerdì 18 Giugno, con “Francesco Nuti. Andata, caduta e ritorno”, scritto e diretto da Valerio Groppa, con Nicola Pecci, le musiche di Giovanni e Francesco Nuti, tratto dall''autobiografia di Francesco Nuti "Sono un bravo ragazzo". Sabato 19 Giugno (alle 17) sarà la volta di “Dante e il Mugello”: Carlo Forasassi conversa con il Dott. Fabrizio Boni, a 700 anni dalla morte di Dante, ad ingresso gratuito. Venerdì 25 Giugno musica protagonista con “Jazz standard band”, con un trio di eccezione composto da Franco Baggiani alla tromba, Alessandro Bruno alla chitarra e Alessandro Geri al contrabbasso. Il giorno seguente sarà la volta del concerto dei “Polimeri Variabili”, con musica prevalentemente funky. Luglio si aprirà il 2 con “I Geneticamente mortificati” in “Restauration. Siamo tornati di moda” monologo imperfetto sull''attualità, scritto da Marco Giavatto e diretto da Fulvio Ferrati. Si proseguirà venerdì 9 Luglio

con “Piccoli crimini coniugali” di Eric Emmanuel Schmitt con Fabrizio Pinzauti e Rosanna Reccia ed il 16 con “La Divina Commedia in 100 luoghi - Inferno Canto XV” performance di Matteo Fratarcangeli. Venerdì 23 Luglio “Musica 60-70-80-90 con Altri Tempi” ad ingresso gratuito ed a chiuder e il mese, il 30, “Dante. Viaggio dentro e intorno alla Divina Commedia” con Gianluigi Tosto. Due gli appuntamenti in agosto: il 6 con “Itaglia” con Matteo Procuranti e Silvia Cuncu per la regia di Virginia Martini ed il 27 “Alla radio con Čechov si può anche ridere” da un''idea di Pietro Venè, con I Pinguini e la regia di Pietro Venè e Cristina Bacci. Venerdì 3 Settembre “New Orleans history” quintetto di fiati e percussioni ed a chiudere, ad ingresso gratuito, venerdì 10 Settembre “Musica dal vivo” con Ivo e Sofia.

“Si tratta di un programma che spazia tra arti e generi molto diversi, spiega soddisfatto il presidente della Pro Loco di San Piero, Sauro Bani, che abbiamo cercato di mettere insieme per accontentare gusti e persone differenti. C’era bisogno di qualcosa che, in sicurezza, ridesse vita alle arti e possibilità di aggregarsi. L’esperienza molto positiva in Villa Adami dello scorso anno ci ha spinto a far crescere questa idea ed a riproporla, diversificando le possibilità di quello che è uno dei luoghi di ritrovo più belli e caratteristici del nostro paese.”

L’accesso, regolamentato, agli spettacoli, avrà un costo di 8 euro a serata (4 euro il ridotto) tranne alcuni appuntamenti ove sia indicato specificatamente l’ingresso gratuito. Le serate, che saranno singolarmente annullate in caso di maltempo, hanno inizio alle 21, prevedono una prenotazione obbligatoria per mail a   prolocosanpieroasieve@gmail.com o attraverso whatsapp al 3382562225 o al 3311090673.','2022-05-09 17:53:34','2022-05-09 17:53:34','prestige1.jpg','/blogs/img','Un ricco programma che accompagnerà sanpierini e visitatori da giugno a settembre, nel segno dell’arte, come occasione di ripartenza...
','Un ricco programma che accompagnerà sanpierini e visitatori da giugno a settembre, nel segno dell’arte, come occasione di ripartenza. E’ davvero ricco il programma di “Venerdì a Villa Adami”, l’iniziativa proposta dalla locale Pro Loco e dal “CCN de’ Medici”, che valorizzerà una delle aree più belle di San Piero a Sieve. Il tutto per dimostrare la propria voglia di non fermarsi, di andare avanti, ma tutto nel rispetto delle norme e senza prendere rischi per spettatori e partecipanti. Una manifestazione che ha avuto il patrocinio del Comune di Scarperia e San Piero ','Villa Adami Venerdi 2021.jpg','Villa Adami Venerdi 2021.jpg');
