# Generated by Django 5.2 on 2025-05-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0013_remove_links_descrisione_alter_links_descrizione"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
